### ISSUE TITLE
Unhandled Runtime Error - Unauthorized

### ISSUE THREAD

**Issue by fotoflo** [vercel-labs/ai-chatbot#68] opened 2023-06-21 07:18 UTC
Your documentation tells us how to configure it but we don't have a url for the github oauth callback.

Somehow it seems to work unauthorized when deployed, but login doesnt work on either local or deployed version.

Unhandled Runtime Error
Error: Unauthorized

Call Stack
eval
node_modules/.pnpm/ai@2.1.2_react@18.2.0_svelte@3.59.1_vue@3.3.4/node_modules/ai/react/dist/index.mjs (120:0)
Generator.next
<anonymous>
fulfilled
node_modules/.pnpm/ai@2.1.2_react@18.2.0_svelte@3.59.1_vue@3.3.4/node_modules/ai/react/dist/index.mjs (22:0)

And on prod:
![image](https://github.com/vercel-labs/ai-chatbot/assets/1642357/967bd26e-8d74-4b57-8c9e-8dbc35d95f94)

**Comment by balazsorban44** [comment] 2023-06-21 07:21
Callback URL: https://github.com/vercel-labs/ai-chatbot/issues/28#issuecomment-1598975610

You are also likely missing a secret in prod, check the server logs as suggested on the image. (logs in the Vercel dashboard)

**Comment by balazsorban44** [comment] 2023-06-21 07:23
Also, this seems to be a duplicate report of #46, although neither has a sufficient reproduction attached. This should likely be closed in favor of #46 and a repro added there, if the above does not resolve your issue. :pray:

**Comment by fotoflo** [comment] 2023-06-21 07:44
Hello, @balazsorban44  thansk for the response 

 i set the NEXTAUTH_URL="localhost:3000" in .env

no luck

**Comment by balazsorban44** [comment] 2023-06-21 08:11
It's likely `NEXTAUTH_SECRET`. See the comments in https://github.com/vercel-labs/ai-chatbot/blob/main/.env.example

For further assistance, please provide a reproduction. :pray:

**Comment by jaredpalmer** [comment] 2023-06-22 17:51
We now force login in all environments as well. This should be fixed. If you are seeing this error still please re-open.

**Closed by jaredpalmer** 2023-06-22 17:51 UTC

**Comment by fotoflo** [comment] 2023-06-26 09:43
Hi I saw you closed this issure without updating the documentation on how to create a secret...

**Comment by prasad123-hub** [comment] 2023-06-27 02:50
Hi .. Facing same issue ... Is there any updated documentation ?
