### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by nkeat12** [vercel-labs/ai-chatbot#26] opened 2023-06-17 03:57 UTC
Have made zero changes to the sample app - it runs, but when you type anything it getting this.

![CleanShot 2023-06-16 at 20 55 13](https://github.com/vercel-labs/ai-chatbot/assets/8729807/7cec74e1-e71e-446d-8752-5fb01804b861)

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Mon May 22 22:52:05 PDT 2023; root:xnu-10002.0.40.505.5~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: 13.4.7-canary.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3

**Comment by CarlosZiegler** [comment] 2023-06-17 12:23
I think you need to add your KV envs. Please try to put your KV envs into .env 
<img width="845" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/38855507/1ae94b3d-26be-45d9-918a-629df146755a">

**Comment by jaredpalmer** [comment] 2023-06-22 17:53
Closing as duplicate of #46 #68 #73. This has been fixed now as we are forcing auth.

**Closed by jaredpalmer** 2023-06-22 17:53 UTC
