### ISSUE TITLE
Edge functions exceed 1MB size

### ISSUE THREAD

**Issue by sarchak** [vercel-labs/ai-chatbot#119] opened 2023-07-29 14:23 UTC
Hello Folks,
I am trying to deploy the current ai-chatbot app to vercel and the deploy is failing with this error.

Error: The Edge Function "share/[id]" size is 1.32 MB and your plan size limit is 1 MB. Learn More: https://vercel.link/edge-function-size

**Comment by zajcomm** [comment] 2023-08-02 12:15
same error!!

**Comment by blazestudios23** [comment] 2023-08-03 04:42
I had the same error, you need a paid account on verbal to fit over 1 MB.

**Comment by ryanyogan** [comment] 2023-08-06 17:03
For sharing, it probably is not what you desire.  However, you can simple run that as a good ol' lambda (serverless) function instead of an edge on Vercel.  Take out the runtime export "const runtime = 'edge'.;". Also make sure any packages you are using, use the node import, not the edge version.  (OpenAI, Prisma, etc)

If it's the first execution in a while, it will have a 3 second cold boot time, if you want free than that probably doesn't bother you for sharing?

**Comment by leerob** [comment] 2023-11-27 00:40
Closing as duplicate of https://github.com/vercel-labs/ai-chatbot/issues/150. You can use the `nodejs` runtime as well 😄

**Closed by leerob** 2023-11-27 00:40 UTC
