### ISSUE TITLE
Vercel Build Error - PPNPM - Resolved

### ISSUE THREAD

**Issue by fotoflo** [vercel-labs/ai-chatbot#67] opened 2023-06-21 07:12 UTC
I tried with the stock deploy button, but didnt work.

Running `pnpm install --no-frozen-lockfile`  fixed the deploy

```
ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.autoInstallPeers" configuration doesn't match the value found in the lockfile
--
15:02:10.314 |  
15:02:10.315 | Update your lockfile using "pnpm install --no-frozen-lockfile"
15:02:10.334 | Error: Command "pnpm install" exited with 1
15:02:10.797 | BUILD_UTILS_SPAWN_1: Command "pnpm install" exited with 1
```

**Comment by balazsorban44** [comment] 2023-06-21 07:16
Duplicate of #58

**Comment by jaredpalmer** [comment] 2023-06-21 18:19
Fixed now! Sorry about that!

**Closed by jaredpalmer** 2023-06-21 18:19 UTC
