### ISSUE TITLE
Cannot deploy the code in Vercel with Hobbyist/free plan

### ISSUE THREAD

**Issue by donvito** [vercel-labs/ai-chatbot#129] opened 2023-08-08 10:08 UTC
Hi, is there any way to try out the code in Vercel in the free plan? 

I am getting this error when deploying.
![Screenshot 2023-08-08 at 6 05 13 PM](https://github.com/vercel-labs/ai-chatbot/assets/890270/bac6f02d-7a9c-42fe-b345-5fbbc8fb3967)

**Comment by Addono** [comment] 2023-10-13 13:09
Just remove all lines which tell it to use Edge works :) 

<img width="1382" alt="image" src="https://github.com/vercel-labs/ai-chatbot/assets/15435678/4fce25a1-6740-4718-ae92-fed64a1b50ee">
_There's a couple more occurrences than those three. But it's just a global-replace in your IDE to get it to work._

**Comment by 0x-Legend** [comment] 2023-10-22 07:24
> Just remove all lines which tell it to use edge works :)
> 
> <img alt="image" width="1382" src="https://user-images.githubusercontent.com/15435678/274909807-4fce25a1-6740-4718-ae92-fed64a1b50ee.png">
> _There's a couple more occurrences than those three. But it's just a global-replace in your IDE to get it to work._
> 
> _Edit: One consequence is though that you will hit the 10 seconds timeout on serverless functions :/_

You can just remove edge runtime from the share and chat opengraph pages. This will prevent the dynamic opengraph image generation, but it will reduce the edge function size by 75% for the 2 pages that hit the hobby tier limit.

**Comment by leerob** [comment] 2023-11-27 00:42
Duplicate of https://github.com/vercel-labs/ai-chatbot/issues/150. But yeah, you can use the Node.js runtime!

**Closed by leerob** 2023-11-27 00:42 UTC
