### ISSUE TITLE
Vercel Build Error

### ISSUE THREAD

**Issue by JacobGoldenArt** [vercel-labs/ai-chatbot#38] opened 2023-06-18 05:02 UTC
I did the one click build, without modifying any code, but when it went to make a build:

Build Failed
The Edge Function "share/[id]" size is 1.32 MB and your plan size limit is 1 MB.

I'm on the hobby plan. Is there a way to decrease the size of this edge function so that I'm
able to use it on the hobby plan?

Thanks! This looks super cool for building off of. Can't wait to dig into it.

**Comment by seraj** [comment] 2023-06-18 05:58
remove [opengraph-image.tsx](https://github.com/vercel-labs/ai-chatbot/blob/main/app/share/%5Bid%5D/opengraph-image.tsx) file on your repo and build it again.

**Comment by SumitBando** [comment] 2023-06-18 08:41
Duplicate of #27
I worked around this by turning off edge runtime for a couple of routes:
```
// export const runtime = 'edge'
```

**Comment by leerob** [comment] 2023-11-27 02:03
Fixed here: https://github.com/vercel-labs/ai-chatbot/pull/186

**Closed by leerob** 2023-11-27 02:03 UTC
